<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class TimelinePengerjaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'knmp_id' => 109,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.29,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.58,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 0.87,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 1.17,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 1.46,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 1.75,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 2.04,
                'bobot_realisasi_kumulatif' => 6.0,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 2.33,
                'bobot_realisasi_kumulatif' => 8.19,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 3.53,
                'bobot_realisasi_kumulatif' => 13.54,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 7.37,
                'bobot_realisasi_kumulatif' => 17.6,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 12.14,
                'bobot_realisasi_kumulatif' => 23.71,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 16.9,
                'bobot_realisasi_kumulatif' => 27.47,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 16.9,
                'bobot_realisasi_kumulatif' => 30.05,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 16.9,
                'bobot_realisasi_kumulatif' => 33.18,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 25.26,
                'bobot_realisasi_kumulatif' => 40.33,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 34.45,
                'bobot_realisasi_kumulatif' => 48.12,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 47.3,
                'bobot_realisasi_kumulatif' => 52.73,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 59.6,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 70.38,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 79.85,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 85.87,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 91.92,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 97.21,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 109,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.7,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 2.06,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 3.41,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 4.76,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 6.11,
                'bobot_realisasi_kumulatif' => 0.84,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 6.88,
                'bobot_realisasi_kumulatif' => 1.32,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 7.68,
                'bobot_realisasi_kumulatif' => 1.54,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 8.47,
                'bobot_realisasi_kumulatif' => 2.37,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 9.44,
                'bobot_realisasi_kumulatif' => 2.68,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 10.42,
                'bobot_realisasi_kumulatif' => 4.19,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 11.41,
                'bobot_realisasi_kumulatif' => 4.98,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 11.41,
                'bobot_realisasi_kumulatif' => 5.4,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 17.93,
                'bobot_realisasi_kumulatif' => 5.4,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 24.46,
                'bobot_realisasi_kumulatif' => 5.4,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 31.28,
                'bobot_realisasi_kumulatif' => 5.4,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 38.1,
                'bobot_realisasi_kumulatif' => 5.4,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 44.92,
                'bobot_realisasi_kumulatif' => 5.4,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 51.73,
                'bobot_realisasi_kumulatif' => 5.4,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 58.55,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 65.12,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 71.7,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 78.27,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 84.85,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 91.42,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 25,
                'bobot_rencana_kumulatif' => 98.6,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 110,
                'periode_mingguan' => 26,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.87,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 1733.0,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 2851.0,
                'bobot_realisasi_kumulatif' => 1697.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 4470.0,
                'bobot_realisasi_kumulatif' => 4387.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 7338.0,
                'bobot_realisasi_kumulatif' => 5744.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 11047.0,
                'bobot_realisasi_kumulatif' => 8999.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 15252.0,
                'bobot_realisasi_kumulatif' => 14010.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 18827.0,
                'bobot_realisasi_kumulatif' => 18509.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 22723.0,
                'bobot_realisasi_kumulatif' => 23491.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 26620.0,
                'bobot_realisasi_kumulatif' => 28990.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 30902.0,
                'bobot_realisasi_kumulatif' => 34472.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 30902.0,
                'bobot_realisasi_kumulatif' => 37552.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 30902.0,
                'bobot_realisasi_kumulatif' => 37552.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 35730.0,
                'bobot_realisasi_kumulatif' => 37552.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 40931.0,
                'bobot_realisasi_kumulatif' => 40020.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 48303.0,
                'bobot_realisasi_kumulatif' => 40600.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 57195.0,
                'bobot_realisasi_kumulatif' => 41921.0,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 67087.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 74998.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 82415.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 89173.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 92195.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 94625.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 97055.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 25,
                'bobot_rencana_kumulatif' => 99046.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 111,
                'periode_mingguan' => 26,
                'bobot_rencana_kumulatif' => 100000.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 1.0,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 1.99,
                'bobot_realisasi_kumulatif' => 2.28,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 3.13,
                'bobot_realisasi_kumulatif' => 5.68,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 4.78,
                'bobot_realisasi_kumulatif' => 8.91,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 6.67,
                'bobot_realisasi_kumulatif' => 11.75,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 8.56,
                'bobot_realisasi_kumulatif' => 16.76,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 11.1,
                'bobot_realisasi_kumulatif' => 20.48,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 14.36,
                'bobot_realisasi_kumulatif' => 24.41,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 17.43,
                'bobot_realisasi_kumulatif' => 27.0,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 20.51,
                'bobot_realisasi_kumulatif' => 30.14,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 24.89,
                'bobot_realisasi_kumulatif' => 31.32,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 24.89,
                'bobot_realisasi_kumulatif' => 31.8,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 24.89,
                'bobot_realisasi_kumulatif' => 32.56,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 29.92,
                'bobot_realisasi_kumulatif' => 32.97,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 35.84,
                'bobot_realisasi_kumulatif' => 33.73,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 43.82,
                'bobot_realisasi_kumulatif' => 35.59,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 64.63,
                'bobot_realisasi_kumulatif' => 39.37,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 73.29,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 81.24,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 88.37,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 91.71,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 94.29,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 96.87,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 112,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 98.9,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.38,
                'bobot_realisasi_kumulatif' => 0.51,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 2.39,
                'bobot_realisasi_kumulatif' => 1.52,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 3.42,
                'bobot_realisasi_kumulatif' => 2.89,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 4.68,
                'bobot_realisasi_kumulatif' => 4.3,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 6.38,
                'bobot_realisasi_kumulatif' => 4.36,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 8.08,
                'bobot_realisasi_kumulatif' => 4.38,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 11.05,
                'bobot_realisasi_kumulatif' => 4.39,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 14.38,
                'bobot_realisasi_kumulatif' => 5.83,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 18.55,
                'bobot_realisasi_kumulatif' => 9.04,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 22.88,
                'bobot_realisasi_kumulatif' => 15.81,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 28.16,
                'bobot_realisasi_kumulatif' => 15.81,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 34.79,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 41.43,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 46.99,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 53.44,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 62.72,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 73.57,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 83.07,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 92.81,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 113,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.09,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.09,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 0.09,
                'bobot_realisasi_kumulatif' => 1.47,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 0.1,
                'bobot_realisasi_kumulatif' => 2.89,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 1.7,
                'bobot_realisasi_kumulatif' => 3.47,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 2.22,
                'bobot_realisasi_kumulatif' => 3.47,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 3.82,
                'bobot_realisasi_kumulatif' => 3.54,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 4.1,
                'bobot_realisasi_kumulatif' => 3.56,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 4.48,
                'bobot_realisasi_kumulatif' => 3.73,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 5.48,
                'bobot_realisasi_kumulatif' => 3.74,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 8.02,
                'bobot_realisasi_kumulatif' => 5.09,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 9.18,
                'bobot_realisasi_kumulatif' => 5.58,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 10.15,
                'bobot_realisasi_kumulatif' => 5.88,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 13.27,
                'bobot_realisasi_kumulatif' => 8.41,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 17.35,
                'bobot_realisasi_kumulatif' => 10.18,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 20.28,
                'bobot_realisasi_kumulatif' => 13.85,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 27.7,
                'bobot_realisasi_kumulatif' => 22.47,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 38.26,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 42.9,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 49.7,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 60.36,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 78.04,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 90.09,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 114,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 95.7,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.15,
                'bobot_realisasi_kumulatif' => 0.04,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.56,
                'bobot_realisasi_kumulatif' => 0.04,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 1.61,
                'bobot_realisasi_kumulatif' => 0.3,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 4.1,
                'bobot_realisasi_kumulatif' => 6.45,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 7.32,
                'bobot_realisasi_kumulatif' => 6.46,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 11.84,
                'bobot_realisasi_kumulatif' => 6.56,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 6.9,
                'bobot_realisasi_kumulatif' => 6.9,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 8.61,
                'bobot_realisasi_kumulatif' => 7.25,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 11.93,
                'bobot_realisasi_kumulatif' => 8.45,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 14.57,
                'bobot_realisasi_kumulatif' => 9.84,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 17.21,
                'bobot_realisasi_kumulatif' => 10.94,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 20.31,
                'bobot_realisasi_kumulatif' => 12.99,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 24.12,
                'bobot_realisasi_kumulatif' => 14.61,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 28.63,
                'bobot_realisasi_kumulatif' => 16.28,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 33.5,
                'bobot_realisasi_kumulatif' => 20.26,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 37.83,
                'bobot_realisasi_kumulatif' => 22.93,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 42.12,
                'bobot_realisasi_kumulatif' => 28.77,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 47.1,
                'bobot_realisasi_kumulatif' => 31.13,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 52.44,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 58.81,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 65.96,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 74.45,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 84.13,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 92.6,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 25,
                'bobot_rencana_kumulatif' => 98.05,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 115,
                'periode_mingguan' => 26,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.32,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.64,
                'bobot_realisasi_kumulatif' => 0.29,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 0.97,
                'bobot_realisasi_kumulatif' => 0.29,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 1.29,
                'bobot_realisasi_kumulatif' => 0.29,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 1.61,
                'bobot_realisasi_kumulatif' => 0.29,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 1.93,
                'bobot_realisasi_kumulatif' => 0.6,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 2.09,
                'bobot_realisasi_kumulatif' => 0.69,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 1.67,
                'bobot_realisasi_kumulatif' => 1.21,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 3.67,
                'bobot_realisasi_kumulatif' => 3.27,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 6.5,
                'bobot_realisasi_kumulatif' => 7.49,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 10.03,
                'bobot_realisasi_kumulatif' => 9.95,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 14.22,
                'bobot_realisasi_kumulatif' => 12.3,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 19.66,
                'bobot_realisasi_kumulatif' => 12.6,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 24.42,
                'bobot_realisasi_kumulatif' => 12.62,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 31.46,
                'bobot_realisasi_kumulatif' => 13.31,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 37.95,
                'bobot_realisasi_kumulatif' => 15.55,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 44.64,
                'bobot_realisasi_kumulatif' => 16.74,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 49.02,
                'bobot_realisasi_kumulatif' => 19.62,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 55.62,
                'bobot_realisasi_kumulatif' => 20.98,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 50.13,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 65.22,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 71.61,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 77.19,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 84.08,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 25,
                'bobot_rencana_kumulatif' => 90.47,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 26,
                'bobot_rencana_kumulatif' => 97.03,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 116,
                'periode_mingguan' => 27,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.02,
                'bobot_realisasi_kumulatif' => 0.02,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 2.18,
                'bobot_realisasi_kumulatif' => 2.66,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 6.39,
                'bobot_realisasi_kumulatif' => 7.94,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 9.92,
                'bobot_realisasi_kumulatif' => 15.87,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 11.92,
                'bobot_realisasi_kumulatif' => 22.46,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 14.72,
                'bobot_realisasi_kumulatif' => 28.48,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 20.26,
                'bobot_realisasi_kumulatif' => 32.39,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 26.99,
                'bobot_realisasi_kumulatif' => 35.96,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 31.21,
                'bobot_realisasi_kumulatif' => 45.3,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 36.61,
                'bobot_realisasi_kumulatif' => 49.03,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 44.26,
                'bobot_realisasi_kumulatif' => 52.3,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 44.26,
                'bobot_realisasi_kumulatif' => 55.56,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 48.08,
                'bobot_realisasi_kumulatif' => 62.74,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 51.27,
                'bobot_realisasi_kumulatif' => 66.54,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 55.2,
                'bobot_realisasi_kumulatif' => 68.01,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 60.13,
                'bobot_realisasi_kumulatif' => 71.08,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 62.72,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 65.46,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 67.82,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 70.84,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 74.62,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 79.15,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 83.2,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 88.95,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 25,
                'bobot_rencana_kumulatif' => 94.95,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 117,
                'periode_mingguan' => 26,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.22,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.43,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 0.65,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 1.13,
                'bobot_realisasi_kumulatif' => 1.53,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 1.6,
                'bobot_realisasi_kumulatif' => 4.1,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 2.55,
                'bobot_realisasi_kumulatif' => 4.47,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 1.23,
                'bobot_realisasi_kumulatif' => 16.03,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 2.25,
                'bobot_realisasi_kumulatif' => 17.05,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 3.68,
                'bobot_realisasi_kumulatif' => 17.69,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 5.31,
                'bobot_realisasi_kumulatif' => 18.66,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 7.88,
                'bobot_realisasi_kumulatif' => 20.14,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 7.88,
                'bobot_realisasi_kumulatif' => 20.14,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 7.88,
                'bobot_realisasi_kumulatif' => 20.14,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 12.86,
                'bobot_realisasi_kumulatif' => 20.14,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 18.12,
                'bobot_realisasi_kumulatif' => 20.28,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 23.79,
                'bobot_realisasi_kumulatif' => 23.34,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 30.93,
                'bobot_realisasi_kumulatif' => 31.57,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 38.2,
                'bobot_realisasi_kumulatif' => 34.66,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 45.48,
                'bobot_realisasi_kumulatif' => 38.24,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 52.75,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 59.61,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 69.5,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 78.16,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 24,
                'bobot_rencana_kumulatif' => 87.1,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 25,
                'bobot_rencana_kumulatif' => 96.04,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 130,
                'periode_mingguan' => 26,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.32,
                'bobot_realisasi_kumulatif' => 0.02,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.63,
                'bobot_realisasi_kumulatif' => 0.02,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 0.95,
                'bobot_realisasi_kumulatif' => 0.06,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 1.27,
                'bobot_realisasi_kumulatif' => 0.35,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 1.58,
                'bobot_realisasi_kumulatif' => 0.37,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 1.9,
                'bobot_realisasi_kumulatif' => 1.44,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 2.22,
                'bobot_realisasi_kumulatif' => 1.64,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 3.18,
                'bobot_realisasi_kumulatif' => 2.75,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 4.15,
                'bobot_realisasi_kumulatif' => 3.37,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 5.11,
                'bobot_realisasi_kumulatif' => 9.3,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 5.11,
                'bobot_realisasi_kumulatif' => 9.3,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 10.83,
                'bobot_realisasi_kumulatif' => 9.56,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 17.2,
                'bobot_realisasi_kumulatif' => 11.44,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 25.77,
                'bobot_realisasi_kumulatif' => 13.31,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 34.33,
                'bobot_realisasi_kumulatif' => 23.79,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 42.9,
                'bobot_realisasi_kumulatif' => 36.1,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 54.6,
                'bobot_realisasi_kumulatif' => 39.63,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 66.82,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 76.34,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 86.09,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 92.52,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 98.04,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 118,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.25,
                'bobot_realisasi_kumulatif' => 0.06,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.5,
                'bobot_realisasi_kumulatif' => 0.1,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 0.74,
                'bobot_realisasi_kumulatif' => 0.14,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 0.99,
                'bobot_realisasi_kumulatif' => 0.18,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 1.24,
                'bobot_realisasi_kumulatif' => 0.25,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 3.62,
                'bobot_realisasi_kumulatif' => 0.68,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 5.99,
                'bobot_realisasi_kumulatif' => 2.12,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 8.37,
                'bobot_realisasi_kumulatif' => 8.68,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 10.74,
                'bobot_realisasi_kumulatif' => 15.25,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 13.12,
                'bobot_realisasi_kumulatif' => 18.03,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 13.12,
                'bobot_realisasi_kumulatif' => 18.03,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 16.49,
                'bobot_realisasi_kumulatif' => 18.23,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 22.63,
                'bobot_realisasi_kumulatif' => 18.88,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 29.77,
                'bobot_realisasi_kumulatif' => 24.45,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 36.92,
                'bobot_realisasi_kumulatif' => 37.38,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 44.06,
                'bobot_realisasi_kumulatif' => 47.91,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 51.81,
                'bobot_realisasi_kumulatif' => 50.65,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 60.27,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 68.73,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 77.2,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 85.78,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 95.52,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 119,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.33,
                'bobot_realisasi_kumulatif' => 0.07,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.65,
                'bobot_realisasi_kumulatif' => 0.08,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 0.98,
                'bobot_realisasi_kumulatif' => 0.09,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 1.31,
                'bobot_realisasi_kumulatif' => 0.61,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 1.63,
                'bobot_realisasi_kumulatif' => 0.86,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 1.96,
                'bobot_realisasi_kumulatif' => 2.47,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 2.28,
                'bobot_realisasi_kumulatif' => 3.91,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 3.19,
                'bobot_realisasi_kumulatif' => 9.57,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 4.09,
                'bobot_realisasi_kumulatif' => 14.23,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 4.99,
                'bobot_realisasi_kumulatif' => 15.22,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 4.99,
                'bobot_realisasi_kumulatif' => 15.22,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 8.35,
                'bobot_realisasi_kumulatif' => 15.27,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 12.12,
                'bobot_realisasi_kumulatif' => 21.12,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 17.4,
                'bobot_realisasi_kumulatif' => 23.14,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 22.68,
                'bobot_realisasi_kumulatif' => 33.1,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 27.96,
                'bobot_realisasi_kumulatif' => 43.0,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 39.93,
                'bobot_realisasi_kumulatif' => 46.01,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 53.43,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 65.4,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 77.06,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 83.35,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 93.62,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 120,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 0.26,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 0.51,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 0.77,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 1.02,
                'bobot_realisasi_kumulatif' => 0.0,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 1.28,
                'bobot_realisasi_kumulatif' => 1.35,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 1.54,
                'bobot_realisasi_kumulatif' => 1.59,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 4.07,
                'bobot_realisasi_kumulatif' => 2.8,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 6.61,
                'bobot_realisasi_kumulatif' => 5.5,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 9.15,
                'bobot_realisasi_kumulatif' => 15.32,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 11.68,
                'bobot_realisasi_kumulatif' => 18.27,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 11.68,
                'bobot_realisasi_kumulatif' => 20.77,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 15.83,
                'bobot_realisasi_kumulatif' => 20.77,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 21.01,
                'bobot_realisasi_kumulatif' => 20.81,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 28.62,
                'bobot_realisasi_kumulatif' => 20.93,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 36.97,
                'bobot_realisasi_kumulatif' => 27.36,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 45.33,
                'bobot_realisasi_kumulatif' => 33.43,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 54.57,
                'bobot_realisasi_kumulatif' => 42.63,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 64.81,
                'bobot_realisasi_kumulatif' => 47.7,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 75.64,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 20,
                'bobot_rencana_kumulatif' => 86.06,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 21,
                'bobot_rencana_kumulatif' => 94.15,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 22,
                'bobot_rencana_kumulatif' => 97.9,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 121,
                'periode_mingguan' => 23,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 1,
                'bobot_rencana_kumulatif' => 3.27,
                'bobot_realisasi_kumulatif' => 3.36,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 2,
                'bobot_rencana_kumulatif' => 8.12,
                'bobot_realisasi_kumulatif' => 6.27,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 3,
                'bobot_rencana_kumulatif' => 12.97,
                'bobot_realisasi_kumulatif' => 10.08,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 4,
                'bobot_rencana_kumulatif' => 18.22,
                'bobot_realisasi_kumulatif' => 13.45,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 5,
                'bobot_rencana_kumulatif' => 23.89,
                'bobot_realisasi_kumulatif' => 16.81,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 6,
                'bobot_rencana_kumulatif' => 27.88,
                'bobot_realisasi_kumulatif' => 20.17,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 7,
                'bobot_rencana_kumulatif' => 30.51,
                'bobot_realisasi_kumulatif' => 23.53,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 8,
                'bobot_rencana_kumulatif' => 37.33,
                'bobot_realisasi_kumulatif' => 26.89,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 9,
                'bobot_rencana_kumulatif' => 44.08,
                'bobot_realisasi_kumulatif' => 30.25,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 10,
                'bobot_rencana_kumulatif' => 51.39,
                'bobot_realisasi_kumulatif' => 33.61,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 11,
                'bobot_rencana_kumulatif' => 58.56,
                'bobot_realisasi_kumulatif' => 36.97,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 12,
                'bobot_rencana_kumulatif' => 64.33,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 13,
                'bobot_rencana_kumulatif' => 71.47,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 14,
                'bobot_rencana_kumulatif' => 76.1,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 15,
                'bobot_rencana_kumulatif' => 81.61,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 16,
                'bobot_rencana_kumulatif' => 87.18,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 17,
                'bobot_rencana_kumulatif' => 92.33,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 18,
                'bobot_rencana_kumulatif' => 96.84,
                'bobot_realisasi_kumulatif' => null,
            ],
            [
                'knmp_id' => 122,
                'periode_mingguan' => 19,
                'bobot_rencana_kumulatif' => 100.0,
                'bobot_realisasi_kumulatif' => null,
            ],
        ];

        // Insert the data into the database in chunks to avoid max placeholder limits
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('tahap_konstruksi')->insert($chunk);
        }
    }
}
